from enum import Enum


class ProcedureScriptEnum(Enum):
    ExpansionPS = "USE [Qiwa_MLSD_Main] \n GO \n DECLARE @return_value int \n EXEC @return_value = [dbo].[" \
                  "Create_NICIssuedVisas_Expansion_Borders] \n @IssuedVisas = N'{{{SoapRp}}}' \n " \
                  "SELECT 'Return Value' = @return_value \n GO "
    EstablishingPS = "USE [Qiwa_MLSD_Main] \n GO \n DECLARE @return_value int \n EXEC    @return_value = [" \
                     "dbo].[Create_NICIssuedVisas_Establishing_Borders] \n" \
                     " @RequestTierId = {{{RequestTierId}}},\n" \
                     " @IssuedVisas = N'{{{SoapRp}}}'\n" \
                     "SELECT    'Return Value' = @return_value \n" \
                     "GO"
    VisitVisaPS = "USE [Qiwa_MLSD_Main] \n GO \n DECLARE @return_value int \n EXEC @return_value = [dbo].[Create_NICIssuedVisas_Visit] " \
                  + " @IssuedVisas = N'{{{SoapRp}}}' \n SELECT 'Return Value' = @return_value \n GO"


class QuriesToGetManual(Enum):
    EstablishingVisaInformation = "select RequestYear,RequestSequence,LaborOfficeId,insertDate,id,RequestedTierId, '{{seq_number}}','LaborOfficeId', {{sevenHundredNo}},{{visasType}} from EstablishingVisaRequest where RequestStatusId != '7' and VisaTotalCount={{totalVisaCount}} and rejectionDescription is null and RequestedTierId in (select id from EstablishingVisaTier with(noLock) where LaborOfficeId = '{{lab_number}}' and EstablishmentSequence = '{{seq_number}}' ) "
    ExpansionVisaInformation = "select top 1 RequestYear,RequestSequence,LaborOfficeId,insertDate,id,Null, EstablishmentSequence ,'LaborOfficeId', {{sevenHundredNo}}, {{visasType}} from ExpansionVisaRequest where RequestStatusId != '2' and VisaTotalCount={{totalVisaCount}} and rejectionDescription is null and LaborOfficeId = '{{lab_number}}' and EstablishmentSequence = '{{seq_number}}' order by insertDate"
    ExpansionVisaInformationZeroBorders = "select top 1 RequestYear,RequestSequence,LaborOfficeId,insertDate,id,Null, EstablishmentSequence ,'LaborOfficeId', {{sevenHundredNo}}, {{visasType}} from ExpansionVisaRequest where VisaOutGoingNumber= {{VisaOutGoingNumber}} and LaborOfficeId = '{{lab_number}}' and EstablishmentSequence = '{{seq_number}}' order by insertDate"
    VisitVisaInformation = "select top 1 RequestYear,RequestSequence,LaborOfficeId,insertDate,id,Null, EstablishmentSequence,'LaborOfficeId', {{sevenHundredNo}}, {{visasType}} from VisitVisaRequest where (rejectionDescription = 'This request are already processed with MOI-Follow-up-No: {{VisaOutGoingNumber}}' or (rejectionDescription is Null and NICRejectionId is Null and VisaOutGoingNumber is Null and VisaTotalCount=0)) and EstablishmentSequence ='{{seq_number}}' and LaborOfficeId='{{lab_number}}' order by InsertDate"
    ExpansionStatus5 = "select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence from ExpansionVisaRequest where RequestStatusId != '2' and RejectionDescription is null  and InsertDate <= '{{endDate}}' and InsertDate >= '{{startDate}}' order by InsertDate Desc"
    EstablishingStatus12 = "select RequestYear,RequestSequence,LaborOfficeId,insertDate,Null,id,RequestedTierId  from EstablishingVisaRequest where RequestStatusId != '7' and rejectionDescription is null and InsertDate <= '{{endDate}}' and InsertDate >= '{{startDate}}' ORDER BY InsertDate Desc"
    VisitVisaMolFollowUp = "select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence from VisitVisaRequest where RejectionDescription like 'This request are already processed with MOI-Follow-up-No:%' and InsertDate <= '{{endDate}}' and InsertDate >= '{{startDate}}' order by InsertDate Desc"
    VisitVisaStatus1 = "select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence from VisitVisaRequest where RequestStatusId = 1 or RejectionDescription like 'This request are already processed with MOI-Follow-up-No:%' and InsertDate <= '{{endDate}}' and InsertDate >= '{{startDate}}' order by InsertDate Desc"
    VisitVisaMolFollowUpByVOGN = "select SUBSTRING(RejectionDescription, 59, 10) from VisitVisaRequest where RejectionDescription like 'This request are already processed with MOI-Follow-up-No:%' order by InsertDate desc"
    SelectVisasLogs = "SELECT top 1 ISNULL(OUT_GOING_RS_MESSAGE,OUT_GOING_RQ_MESSAGE) FROM [MCR_Log_v0{{MCR_VERSION}}].[dbo].[{{tableName}}] with(nolock) where SERVICE_CODE = 'NSVR0001' and (OUT_GOING_RS_MESSAGE like '%{{OrderNumber}}</a:OrderNumber>%'  or OUT_GOING_RQ_MESSAGE like '%{{OrderNumber}}</a:OrderNumber>%') and (OUT_GOING_RS_MESSAGE like '%{{OrderYear}}</a:OrderYear>%' or OUT_GOING_RQ_MESSAGE like '%{{OrderYear}}</a:OrderYear>%') and (OUT_GOING_RS_MESSAGE like '%{{LabourOfficeCode}}</a:LabourOfficeCode>%' or OUT_GOING_RQ_MESSAGE like '%{{LabourOfficeCode}}</a:LabourOfficeCode>%') and (OUT_GOING_RQ_MESSAGE is not Null or OUT_GOING_RS_MESSAGE is not Null) order by ESB_LOGGER_ID desc"
    VisaInfoByOrderInfo = "DECLARE @OrderYear AS VARCHAR(100)='{{OrderYear}}'\n DECLARE @LaborOfficeId AS VARCHAR(100)='{{LabourOfficeCode}}'\n DECLARE @OrderNumber AS VARCHAR(100)='{{OrderNumber}}'\n select * from\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence,id,Null as RequestedTierId, '2' as VisaTypeId from VisitVisaRequest where RequestSequence =@OrderNumber and LaborOfficeId=@LaborOfficeId and RequestYear=@OrderYear ) a union\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence,id,Null as RequestedTierId, '3' as VisaTypeId from ExpansionVisaRequest where RequestSequence =@OrderNumber and LaborOfficeId=@LaborOfficeId and RequestYear=@OrderYear) union\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,Null as EstablishmentSequence ,id,RequestedTierId, '1' as VisaTypeId  from EstablishingVisaRequest where RequestSequence =@OrderNumber and LaborOfficeId=@LaborOfficeId and RequestYear=@OrderYear)"
    CheckIfEstHasVisaIssues = "select * from\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence,id,Null as RequestedTierId, '2' as VisaTypeId from VisitVisaRequest where RejectionDescription like 'This request are already processed with MOI-Follow-up-No:%' and EstablishmentSequence ='{{EstablishmentSequence}}' and LaborOfficeId='{{LaborOfficeId}}' ) a union\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,EstablishmentSequence,id,Null as RequestedTierId, '3' as VisaTypeId from ExpansionVisaRequest where RequestStatusId in (5,3) and RejectionDescription is null and EstablishmentSequence ='{{EstablishmentSequence}}' and LaborOfficeId='{{LaborOfficeId}}') union\n ( select RequestYear,RequestSequence,LaborOfficeId,insertDate,'{{EstablishmentSequence}}' as EstablishmentSequence ,id,RequestedTierId, '1' as VisaTypeId  from EstablishingVisaRequest where RequestStatusId in (12,8) and RejectionDescription is null and RequestedTierId in (select id from EstablishingVisaTier where EstablishmentSequence='{{EstablishmentSequence}}' and LaborOfficeId = '{{LaborOfficeId}}'))"


class SoapResTemplatesEnum(Enum):
    EstTemp = "<SOAP_Domain_Msg xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">\n\t<Context operation=\"IssueVisa\"\n\t         operationType=\"GATEWAY\"\n\t         portType=\"\"\n\t         portTypeNamespace=\"\"\n\t         port=\"\"\n\t         service=\"ComIbmBrokerGenericGatewayService\"\n\t         fileName=\"\">\n\t\t<SOAP_Version>1.1</SOAP_Version>\n\t\t<Namespace xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"/>\n\t\t<_XmlDeclaration Version=\"1.0\"\n\t\t                 Encoding=\"UTF-8\"/>\n\t</Context>\n\t<Header/>\n\t<Body>\n\t\t<IssueVisaResponse xmlns=\"urn:MOI.NIC.eServices-V1\">\n\t\t\t<IssueVisaResult xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t                 xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t{{BodyPlaceHolder}}\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:NICVisaDate>{{HijriNICVisaDate}}</a:NICVisaDate>\n\t\t\t\t<a:NICVisaNumber>{{NICVisaNumber}}</a:NICVisaNumber>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:RequestTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:RequestTimestamp>\n\t\t\t\t<a:ResponseTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:ResponseTimestamp>\n\t\t\t</IssueVisaResult>\n\t\t\t<req xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t     xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t<a:ApprovedByIDNumber>1010101010</a:ApprovedByIDNumber>\n\t\t\t\t<a:ClientIpAddress>10.240.170.50</a:ClientIpAddress>\n\t\t\t\t<a:CompanyNumber>{{CompanyNumber}}</a:CompanyNumber>\n\t\t\t\t<a:EstablishmentOrCompanyID>{{SevenHundred}}</a:EstablishmentOrCompanyID>\n\t\t\t\t<a:IssueVisaReqDetails>\n\t\t\t\t\t{{IssueVisaReqDetails}}\n\t\t\t\t\t\n\t\t\t\t</a:IssueVisaReqDetails>\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:LabourOfficeCompany>{{LabourOfficeCode}}</a:LabourOfficeCompany>\n\t\t\t\t<a:LocationCode>1730</a:LocationCode>\n\t\t\t\t<a:OperatorId>1010101010</a:OperatorId>\n\t\t\t\t<a:OrderDate>{{HijriNICVisaDate}}</a:OrderDate>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:ReasonAddActivity>0</a:ReasonAddActivity>\n\t\t\t\t<a:ReasonExtendedActivity>0</a:ReasonExtendedActivity>\n\t\t\t\t<a:ReasonFinalExit>0</a:ReasonFinalExit>\n\t\t\t\t<a:ReasonGovernmentContract>0</a:ReasonGovernmentContract>\n\t\t\t\t<a:ReasonNewCompany>1</a:ReasonNewCompany>\n\t\t\t\t<a:ReasonPrivateContract>0</a:ReasonPrivateContract>\n\t\t\t\t<a:ReasonSeasonalEmployee>0</a:ReasonSeasonalEmployee>\n\t\t\t\t<a:ReasonVisaNotUsed>0</a:ReasonVisaNotUsed>\n\t\t\t\t<a:VisaType>2</a:VisaType>\n\t\t\t</req>\n\t\t</IssueVisaResponse>\n\t</Body>\n</SOAP_Domain_Msg>"
    VVTemp = "<SOAP_Domain_Msg xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">\n\t<Context operation=\"IssueVisa\"\n\t         operationType=\"GATEWAY\"\n\t         portType=\"\"\n\t         portTypeNamespace=\"\"\n\t         port=\"\"\n\t         service=\"ComIbmBrokerGenericGatewayService\"\n\t         fileName=\"\">\n\t\t<SOAP_Version>1.1</SOAP_Version>\n\t\t<Namespace xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"/>\n\t\t<_XmlDeclaration Version=\"1.0\"\n\t\t                 Encoding=\"UTF-8\"/>\n\t</Context>\n\t<Header/>\n\t<Body>\n\t\t<IssueVisaResponse xmlns=\"urn:MOI.NIC.eServices-V1\">\n\t\t\t<IssueVisaResult xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t                 xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t{{BodyPlaceHolder}}\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:NICVisaDate>{{HijriNICVisaDate}}</a:NICVisaDate>\n\t\t\t\t<a:NICVisaNumber>{{NICVisaNumber}}</a:NICVisaNumber>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:RequestTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:RequestTimestamp>\n\t\t\t\t<a:ResponseTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:ResponseTimestamp>\n\t\t\t</IssueVisaResult>\n\t\t\t<req xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t     xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t<a:ApprovedByIDNumber>1010101010</a:ApprovedByIDNumber>\n\t\t\t\t<a:ClientIpAddress>10.240.170.50</a:ClientIpAddress>\n\t\t\t\t<a:CompanyNumber>{{CompanyNumber}}</a:CompanyNumber>\n\t\t\t\t<a:EstablishmentOrCompanyID>{{SevenHundred}}</a:EstablishmentOrCompanyID>\n\t\t\t\t<a:IssueVisaReqDetails>\n\t\t\t\t\t{{IssueVisaReqDetails}}\n\t\t\t\t\t\n\t\t\t\t</a:IssueVisaReqDetails>\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:LabourOfficeCompany>{{LabourOfficeCode}}</a:LabourOfficeCompany>\n\t\t\t\t<a:LocationCode>1730</a:LocationCode>\n\t\t\t\t<a:OperatorId>1010101010</a:OperatorId>\n\t\t\t\t<a:OrderDate>{{HijriNICVisaDate}}</a:OrderDate>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:ReasonAddActivity>0</a:ReasonAddActivity>\n\t\t\t\t<a:ReasonExtendedActivity>0</a:ReasonExtendedActivity>\n\t\t\t\t<a:ReasonFinalExit>0</a:ReasonFinalExit>\n\t\t\t\t<a:ReasonGovernmentContract>0</a:ReasonGovernmentContract>\n\t\t\t\t<a:ReasonNewCompany>0</a:ReasonNewCompany>\n\t\t\t\t<a:ReasonPrivateContract>0</a:ReasonPrivateContract>\n\t\t\t\t<a:ReasonSeasonalEmployee>1</a:ReasonSeasonalEmployee>\n\t\t\t\t<a:ReasonVisaNotUsed>0</a:ReasonVisaNotUsed>\n\t\t\t\t<a:VisaType>4</a:VisaType>\n\t\t\t</req>\n\t\t</IssueVisaResponse>\n\t</Body>\n</SOAP_Domain_Msg>"
    ExpTemp = "<SOAP_Domain_Msg xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">\n\t<Context operation=\"IssueVisa\"\n\t         operationType=\"GATEWAY\"\n\t         portType=\"\"\n\t         portTypeNamespace=\"\"\n\t         port=\"\"\n\t         service=\"ComIbmBrokerGenericGatewayService\"\n\t         fileName=\"\">\n\t\t<SOAP_Version>1.1</SOAP_Version>\n\t\t<Namespace xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"/>\n\t\t<_XmlDeclaration Version=\"1.0\"\n\t\t                 Encoding=\"UTF-8\"/>\n\t</Context>\n\t<Header/>\n\t<Body>\n\t\t<IssueVisaResponse xmlns=\"urn:MOI.NIC.eServices-V1\">\n\t\t\t<IssueVisaResult xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t                 xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t{{BodyPlaceHolder}}\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:NICVisaDate>{{HijriNICVisaDate}}</a:NICVisaDate>\n\t\t\t\t<a:NICVisaNumber>{{NICVisaNumber}}</a:NICVisaNumber>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:RequestTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:RequestTimestamp>\n\t\t\t\t<a:ResponseTimestamp>{{IssuedDate}}T00:00:00.000000+03:00</a:ResponseTimestamp>\n\t\t\t</IssueVisaResult>\n\t\t\t<req xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t\t     xmlns:a=\"http://schemas.datacontract.org/2004/07/SamisObjectModel\">\n\t\t\t\t<a:ApprovedByIDNumber>1010101010</a:ApprovedByIDNumber>\n\t\t\t\t<a:ClientIpAddress>10.240.170.50</a:ClientIpAddress>\n\t\t\t\t<a:CompanyNumber>{{CompanyNumber}}</a:CompanyNumber>\n\t\t\t\t<a:EstablishmentOrCompanyID>{{SevenHundred}}</a:EstablishmentOrCompanyID>\n\t\t\t\t<a:IssueVisaReqDetails>\n\t\t\t\t\t{{IssueVisaReqDetails}}\n\t\t\t\t\t\n\t\t\t\t</a:IssueVisaReqDetails>\n\t\t\t\t<a:LabourOfficeCode>{{LabourOfficeCode}}</a:LabourOfficeCode>\n\t\t\t\t<a:LabourOfficeCompany>{{LabourOfficeCode}}</a:LabourOfficeCompany>\n\t\t\t\t<a:LocationCode>1730</a:LocationCode>\n\t\t\t\t<a:OperatorId>1010101010</a:OperatorId>\n\t\t\t\t<a:OrderDate>{{HijriNICVisaDate}}</a:OrderDate>\n\t\t\t\t<a:OrderNumber>{{OrderNumber}}</a:OrderNumber>\n\t\t\t\t<a:OrderYear>{{OrderYear}}</a:OrderYear>\n\t\t\t\t<a:ReasonAddActivity>1</a:ReasonAddActivity>\n\t\t\t\t<a:ReasonExtendedActivity>0</a:ReasonExtendedActivity>\n\t\t\t\t<a:ReasonFinalExit>0</a:ReasonFinalExit>\n\t\t\t\t<a:ReasonGovernmentContract>0</a:ReasonGovernmentContract>\n\t\t\t\t<a:ReasonNewCompany>0</a:ReasonNewCompany>\n\t\t\t\t<a:ReasonPrivateContract>0</a:ReasonPrivateContract>\n\t\t\t\t<a:ReasonSeasonalEmployee>0</a:ReasonSeasonalEmployee>\n\t\t\t\t<a:ReasonVisaNotUsed>0</a:ReasonVisaNotUsed>\n\t\t\t\t<a:VisaType>2</a:VisaType>\n\t\t\t</req>\n\t\t</IssueVisaResponse>\n\t</Body>\n</SOAP_Domain_Msg>"


class VisaTypeEnum(Enum):
    EstVisa = 1
    VVisa = 2
    ExpVisa = 3


class VisaStatusEnum(Enum):
    status1 = 'غير مستخدم'
    status2 = 'ملغي'
    status3 = 'مستخدم'
    status4 = 'بإنتظار الإلغاء من وزارة الداخلية'


class CancelReason(Enum):
    EstingViol = 'تم إلغاء التأشيرات الخاصة بكم نتيجة عدم الالتزام بالتوطين المطلوب بعد انتهاء فترة السماح. علمًا بأن منشأتك في النطاق الأحمر وذلك ينافي شروط الاستفادة من برنامج التأسيس.'
    Expired = 'تم إلغاؤها تلقائياً من قبل وزارة الداخلية لإنتهاء صلاحيتها و مرور أكثر من 720 يوم من تاريخ إصدارها '
    Error = 'نأسف لإبلاغك بأنه تم إلغاؤها تلقائياً من وزارة الداخلية لوجود مشكلة في بيانات التأشيرة, حيث معلومات التأشيرة يجب أن تكون مطابقة للبيانات في وزارة الداخلية و لم تكن المعلومات المسجلة على التأشيرة مطابقة لمعلومات وزارة الداخلية'
    Normal = ' تم إرسال طلب إلغاؤها بتاريخ {{CancelRequestDt}} وتم إلغاؤها بتاريخ {{CanceledDt}}'
